name: Artwork from a contribution graph
on:
  push:
  schedule:
    - cron: "* */24 * * *"

jobs:
  build:
    name: Make artwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jasineri/gitartwork@v1
        with:
          user_name: hesam-init
          text: Hesam
      - uses: jasineri/simple-push-action@v1
